api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from .views import (
                    OrderList,
                    OrderDetail,
                    OrderItemList,
                    CouponList,
                    CouponDetail,
                    OrderItemDetail,
                    CategoryList,
                    CategoryDetail,
                    ProductList,
                    ProductDetail
                    )
from .views import api_root


urlpatterns = format_suffix_patterns([
    # Main page
    path('', api_root, name='main'),

    # Orders
    path('orders/', OrderList.as_view(), name='order-list'),
    path('order/<int:pk>/', OrderDetail.as_view(), name='order-detail'),

    #Order items
    path('order-item/', OrderItemList.as_view(), name='order_item-list'),
    path('order-item/<int:pk>/detail', OrderItemDetail.as_view(), name='orderitem-detail'),

    # Coupons
    path('coupons/<int:pk>/detail', CouponDetail.as_view(), name='coupon-detail'),
    path('coupons/', CouponList.as_view(), name='coupon-list'),

    # Category
    path('category/', CategoryList.as_view(), name='category-list'),
    path('category/<int:pk>/detail/', CategoryDetail.as_view(), name='category-detail'),

    # Products
    path('products/', ProductList.as_view(), name='product-list'),
    path('products/<int:pk>/detail/', ProductDetail.as_view(), name='product-detail'),
])

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove')
]

coupons/urls.py
from django.urls import path

from .views import apply_coupon

app_name = 'coupons'
urlpatterns = [
    path('apply/', apply_coupon, name='apply_coupon')
]

ecommerce_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('api/v1/', include('api.urls')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='create_order')
]

shop/urls.py
from django.urls import path

from .views import product_list, product_detail

app_name = 'shop'
urlpatterns = [
    path('', product_list, name='product_list'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('product/<int:id>/<slug:slug>/', product_detail, name='product_detail'),
]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from .cart import Cart
from shop.models import Product
from coupons.forms import ApplyCouponForm
from .forms import CartAddProductForm

# Create your views here.


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    form = CartAddProductForm(request.POST)
    if form.is_valid():
        quantity = form.cleaned_data['quantity']
        override = form.cleaned_data['override']
        cart.add(product, quantity=quantity, override_quantity=override)
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    coupon_form = ApplyCouponForm()
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True
        })
    return render(request, 'cart/cart_detail.html', {'cart': cart, 'coupon_form': coupon_form})

templates/cart/cart_detail.html
{% extends 'shop/base.html' %}

{% block title %}
    Ваша корзина
{% endblock %}

{% block content %}
    <section class="cart-wrapper">
        <h1>Ваша корзина</h1>
        <table class="cart">
            <thead>
            <tr>
                <th>Изображение</th>
                <th>Товар</th>
                <th>Количество</th>
                <th>Удалить</th>
                <th>Стоимость товара</th>
                <th>Цена</th>
            </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                    {% with product=item.product %}
                        <tr>
                            <td>
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{{ product.image.url }}" alt="">
                                </a>
                            </td>
                            <td>{{ product.name }}</td>
                            <td>
                                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.override }}
                                    <input type="submit" value="Обновить">
                                </form>
                            </td>
                            <td>
                                <form action="{% url 'cart:cart_remove' product.id%}" method="post">
                                    {% csrf_token %}
                                    <input type="submit" value="Удалить">
                                </form>
                            </td>
                            <td class="num">${{ item.price }}</td>
                            <td class="num">${{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                {% if cart.coupon %}
                    <tr class="subtotal">
                        <td></td>
                        <td colspan="4"></td>
                        <td class="num">${{ cart.get_total_price }}</td>
                    </tr>
                    <tr>
                        <td>
                            Купон "{{ cart.coupon.code }} - {{ cart.coupon.discount }}"
                        </td>
                        <td colspan="4"></td>
                        <td class="neg">-${{ cart.get_discount }}</td>
                    </tr>
                {% endif %} 
                <tr class="total">
                    <td>Итого</td>
                    <td colspan="4"></td>
                    <td class="num">${{ cart.get_total_price_after_discount }}</td>
                </tr>
            </tbody>
        </table>
        <p>Использовать Купон</p>
        <form action="{% url 'coupons:apply_coupon' %}" method="post">
         {% csrf_token %}
            {{ coupon_form.as_p }}
            <input type="submit" value="Использовать">
        </form>
        <p class="text-right">
            <a href="{% url 'shop:product_list' %}">Продолжить покупки</a>
            <a href="{% url 'orders:create_order' %}">Перейти к оформлению</a>
        </p>
    </section>
{% endblock %}